export enum wsPackageTypes {
  TABLE_UPDATE_REQUEST = 'TABLE_UPDATE_REQUEST',
  TABLE_STROP_UPDATE_REQUEST = 'TABLE_STROP_UPDATE_REQUEST',
  TABLE_UPDATE_STATUS = 'TABLE_UPDATE_STATUS',
  WEBSOСKET_ERROR = 'WEBSOСKET_ERROR',
  WEBSOСKET_INFO = 'WEBSOСKET_INFO',
}
